name: CI

on:
  workflow_dispatch: ~
  pull_request: ~
  release:
    types: [created]
  schedule:
    - cron: "0 1 * * 6" # Run at 1am every Saturday

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    name: "PHP ${{ matrix.php }}"

    strategy:
      fail-fast: false
      matrix:
        php: ["7.4", "8.0", "8.1"]

    steps:

      # --- ⚙️ Setup ⚙️ ----------

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          extensions: intl
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.PAT }}

      - name: 'Get Composer cache directory'
        id: composer-cache
        run: 'echo "::set-output name=dir::$(composer config cache-files-dir)"'

      - name: 'Cache Composer'
        uses: actions/cache@v2
        with:
          path: '${{ steps.composer-cache.outputs.dir }}'
          key: "${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-composer-

      - name: 'Install PHP dependencies'
        run: 'composer update --no-interaction --no-progress --verbose --ansi'

      # --- 🛠 Test 🛠 ----------

      - name: 'Validate composer.json'
        run: 'composer validate --ansi --strict'

      - name: 'Run PHPStan'
        run: 'vendor/bin/phpstan analyse --error-format=github --no-interaction --no-progress --ansi'

      - name: 'Run ECS'
        run: 'vendor/bin/ecs check tests ecs.php --no-interaction --no-progress-bar --ansi'

      - uses: actions/cache@v2
        with:
          path: ~/.symfony/cache
          key: ${{ runner.os }}-php-${{ matrix.php }}
          restore-keys: ${{ runner.os }}-php-
